### ISSUE TITLE
ImportError: cannot import name 'url' from 'django.conf.urls'

### ISSUE THREAD

**Issue by snipher-marube** [yeazin/Multi-Authors-advanced-Django-Blog#7]
**Description of the bug**
After upgrading Django to version 4.2.1, an import error occurs when running the server. The error message states:
`File "Multi-Authors-advanced-Django-Blog/src/urls.py", line 4, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/home/username/blog/.env/lib/python3.11/site-packages/django/conf/urls/__init__.py)`

**To Reproduce**
1. Upgrade Django to the latest version (django==4.2.1).
2. Run the server.
3. Observe the import error.

**Expected behavior**
The server should run successfully without any import errors after upgrading Django to version 4.2.1.

**solution**
In Django 4.0 and above, the url function has been deprecated and replaced with the path function. To resolve the import error, you need to update the code in the Multi-Authors-advanced-Django-Blog/src/urls.py file.

Replace the line `from django.conf.urls import url` with the following line:

`from django.urls import path`

since the above line is already imported all you need is to remove  this line
`from django.conf.urls import url`

Make sure to update any URLs defined using the old `url` function to use `path` instead. This change is necessary due to the deprecation of the `url` function in Django 4.0 and above.

**Comment by yeazin** [comment]
This is because the current project version was below django-4.
Thanks for your observation on this. I will fix this issue update the code next time.
If you need any discussion further Please Contact me .

email : [naz.yeasin@gmail.com](mailto:naz.yeasin@gmail.com)
fb : facebook.com/yeazin.io
