### ISSUE TITLE
Warning: Auto-created primary key used without defining a primary key type in Django models

### ISSUE THREAD

**Issue by snipher-marube** [yeazin/Multi-Authors-advanced-Django-Blog#8]
**Warning description**
When running the project, the following warning messages are displayed:

`WARNINGS:
blog.Blog: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the BlogConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
blog.Category: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the BlogConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
blog.Comment: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the BlogConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
...
`

**To Reproduce**
1. Run the project.
2. Observe the warning messages mentioned above.

**Expected behavior**
The project should not display any warning messages regarding the auto-created primary key.

**Solution**
To address these warnings, you can add the following line to your `settings.py` file:

`DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'`

This configuration specifies the default auto field type as BigAutoField, which is a subclass of AutoField. By setting this value, you indicate that you want to use BigAutoField as the primary key type for the affected models (e.g., Blog, Category, Comment, etc.).

Adding this line to your `settings.py` file should resolve the warnings related to the auto-created primary key.

**Comment by yeazin** [comment]
This is because the current project version was below django-4. 
Thanks for your observation on this. I will fix this issue update the code next time. 
If you need any discussion further Please Contact me .

email : naz.yeasin@gmail.com
fb : facebook.com/yeazin.io
